### ISSUE TITLE
Hamburger doesn't collapse menu

### ISSUE THREAD

**Issue by juliankay** [MichaelGillett/GuidelinesDev#1]
When then window is large enough for the menu to be open, clicking on the hamburger doesn't collapse it as expected (based on behaviour of other Windows apps).

It does collapse when the window is smaller though, and clicking on it produces a fly out as expected.

However, clicking on it then resizing produces odd results. See below:

![yummy-hamburgers](https://cloud.githubusercontent.com/assets/952538/12351585/83a367a8-bb76-11e5-910e-3cb1c7a00cc8.gif)

**Comment by MichaelGillett** [comment]
Thanks for the feedback, I was currently aware of that. That was on my list of tweaks to make and now it is my next thing to do ;)

**Comment by MichaelGillett** [comment]
Latest release resolves this issue, the sidebar should now close on window resize. The sidebar can also be collapsed to just icons when it is maximised by default.
